### PR TITLE
appveyor

### PR DESCRIPTION
**Pull request by JayBazuzi**

### CODE REVIEW

**Comment by claremacrae** [comment]
Thanks for this. This looks good to me.

I see it selects VS 2015, and I know that the Google Test and Catch2 code builds also with VS2017, so it would be really nice to have CI builds of both...

Hi @isidore - do you have an Appveyor account already? I'd be happy to set one up, but I think it would be better if it were done in your name, e.g. for consistency with the TravisCI one.

**Comment by JayBazuzi** [comment]
Have you found many cases where something works w/ VS2015, but not with VS2017? For the most part, I expect back-compatibility.

**Comment by claremacrae** [comment]
So far I’m more familiar with VS2013 at work - only just started using VS2017.
However, I had noticed this nice approach of testing on multiple different versions of VS, and wondered if that might be something to try out here as a later step:
https://github.com/rockdreamer/throwing_ptr/blob/master/appveyor.yml

**Comment by JayBazuzi** [comment]
Yep, using a matrix is certainly a viable option.

**Pull request merged**
